name: Fund_Arbitrage_Patrol

on:
  schedule:
    # 周一到周五 北京时间 10:20 (UTC 2:20)
    - cron: '20 2 * * 1-5'
    # 周一到周五 北京时间 10:35 (UTC 2:35)  
    - cron: '35 2 * * 1-5'
  workflow_dispatch:
jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests urllib3

      - name: Run Script
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          RECEIVER: ${{ secrets.RECEIVER }}
        run: python 基金套利.py
